"""gestores, medidores y lecturas

Revision ID: 235f0b28e7b9
Revises: a1c3d9f0b2e4
Create Date: 2026-10-02 14:40:01.985561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '235f0b28e7b9'
down_revision: Union[str, Sequence[str], None] = 'a1c3d9f0b2e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gestores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_gestor_tenant_email')
    )
    op.create_table('meters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=64), nullable=False),
    sa.Column('tipo', sa.String(length=16), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('unidad', sa.String(length=16), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'codigo', name='uq_meter_tenant_codigo')
    )
    with op.batch_alter_table('meters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meters_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('meter_id', sa.Integer(), nullable=False),
    sa.Column('gestor_id', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('valor_anterior', sa.Float(), nullable=True),
    sa.Column('consumo', sa.Float(), nullable=True),
    sa.Column('foto_url', sa.String(length=500), nullable=True),
    sa.Column('ocr_valor', sa.String(length=32), nullable=True),
    sa.Column('ocr_confianza', sa.Float(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('anomala', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gestor_id'], ['gestores.id'], ),
    sa.ForeignKeyConstraint(['meter_id'], ['meters.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('readings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_readings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_readings_meter_id'), ['meter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_readings_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('readings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_readings_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_readings_meter_id'))
        batch_op.drop_index(batch_op.f('ix_readings_created_at'))

    op.drop_table('readings')
    with op.batch_alter_table('meters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meters_tenant_id'))

    op.drop_table('meters')
    op.drop_table('gestores')
    # ### end Alembic commands ###
