"""add mercado pago connect fields to tenants

Revision ID: 9867beb758c4
Revises: 235f0b28e7b9
Create Date: 2026-10-02 16:41:29.010500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9867beb758c4'
down_revision: Union[str, Sequence[str], None] = '235f0b28e7b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('mp_preference_id', sa.String(length=128), nullable=True))
    op.add_column('invoices', sa.Column('mp_payment_id', sa.String(length=128), nullable=True))
    op.add_column('tenants', sa.Column('mp_user_id', sa.String(length=64), nullable=True))
    op.add_column('tenants', sa.Column('mp_access_token', sa.String(length=1000), nullable=True))
    op.add_column('tenants', sa.Column('mp_refresh_token', sa.String(length=1000), nullable=True))
    op.add_column('tenants', sa.Column('mp_public_key', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('mp_token_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'mp_token_expires_at')
    op.drop_column('tenants', 'mp_public_key')
    op.drop_column('tenants', 'mp_refresh_token')
    op.drop_column('tenants', 'mp_access_token')
    op.drop_column('tenants', 'mp_user_id')
    op.drop_column('invoices', 'mp_payment_id')
    op.drop_column('invoices', 'mp_preference_id')
    # ### end Alembic commands ###
